name: 3DFSC
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex
  - appdirs
  - blas
  - ca-certificates
  - cudatoolkit
  - cycler
  - dask-core
  - dbus
  - expat
  - fontconfig
  - freetype
  - glib
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf5
  - icu
  - imageio
  - jbig
  - jpeg
  - libffi
  - libgcc
  - libgcc-ng
  - libgfortran
  - libgfortran-ng
  - libiconv
  - libpng
  - libtiff
  - libxcb
  - libxml2
  - llvmlite
  - matplotlib
  - mkl
  - networkx
  - numba
  - olefile
  - openssl
  - pcre
  - pillow
  - pip
  - pyparsing
  - pyqt
  - python=3.6.2
  - pywavelets
  - qt
  - readline
  - scikit-image
  - scipy
  - sip
  - sqlite
  - tk
  - toolz
  - wheel
  - xz
  - zlib
  - pip:
    - amqp==2.2.1
    - anyjson==0.3.3
    - asn1crypto==0.22.0
    - autopep8==1.3.3
    - babel==2.5.3
    - bcrypt==3.1.3
    - billiard==3.5.0.3
    - botocore==1.6.5
    - cached-property==1.3.1
    - celery==4.1.0
    - certifi==2019.6.16
    - cffi==1.10.0
    - chardet==3.0.4
    - click==6.7
    - colorama==0.3.7
    - cryptography==2.0.3
    - decorator==4.4.0
    - django==1.10.7
    - django-bootstrap3==9.0.0
    - django-debug-toolbar==1.9.1
    - django-fileprovider==0.1.4
    - django-registration==2.2
    - django-sendfile==0.3.11
    - docker==2.7.0
    - docker-compose==1.18.0
    - docker-pycreds==0.2.1
    - dockerpty==0.4.1
    - docopt==0.6.2
    - docutils==0.14
    - flower==0.9.2
    - gunicorn==19.7.1
    - idna==2.6
    - jinja2==2.10
    - jmespath==0.9.3
    - jsonschema==2.6.0
    - kombu==4.1.0
    - mako==1.1.0
    - markupsafe==1.1.1
    - mrcfile==1.0.0
    - numpy==1.17.0
    - nvidia-docker-compose==0.1.5
    - paramiko==2.2.1
    - psycopg2==2.7.4
    - psycopg2-binary==2.7.4
    - py==1.4.34
    - pyasn1==0.3.2
    - pycodestyle==2.3.1
    - pycparser==2.18
    - pycuda==2019.1.2
    - pyflakes==1.6.0
    - pyminizip==0.2.1
    - pynacl==1.1.2
    - pytest==3.2.3
    - python-dateutil==2.8.0
    - pytools==2019.1.1
    - pytz==2019.2
    - pyyaml==3.12
    - redis==2.10.5
    - requests==2.18.4
    - rsa==3.4.2
    - s3transfer==0.1.10
    - scikit-cuda==0.5.1
    - selenium==3.4.3
    - setuptools==41.0.1
    - six==1.12.0
    - sqlparse==0.2.4
    - texttable==0.9.1
    - tornado==5.0
    - urllib3==1.22
    - uwsgi==2.0.15
    - vine==1.1.4
    - websocket-client==0.46.0

